#!/usr/bin/env bash
set -euo pipefail
PATCH="TAMIYOUZ-WP-DEVELOPER-HUB-V1_1-READONLY-REVIEW"
ROOT="${WP_ROOT:-$PWD}"
BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_ROOT="$BASE/src/tamiyouz-developer-hub.php"
SRC_ADMIN="$BASE/src/tamiyouz-developer-hub/admin.php"
SRC_BASE="$BASE/src/tamiyouz-developer-hub/base.php"
SRC_REVIEW="$BASE/src/tamiyouz-developer-hub/review.php"
DEST_ROOT="$ROOT/wp-content/mu-plugins/tamiyouz-developer-hub.php"
DEST_DIR="$ROOT/wp-content/mu-plugins/tamiyouz-developer-hub"
[[ -f "$ROOT/wp-config.php" ]] || { echo "ERROR=SET_WP_ROOT"; exit 1; }
php -l "$SRC_ROOT"
php -l "$SRC_ADMIN"
php -l "$SRC_BASE"
php -l "$SRC_REVIEW"
mkdir -p "$DEST_DIR"
[[ -f "$DEST_ROOT" ]] && cp -a "$DEST_ROOT" "$DEST_ROOT.bak.$(date +%Y%m%d-%H%M%S)"
cp "$SRC_ROOT" "$DEST_ROOT"
cp "$SRC_ADMIN" "$DEST_DIR/admin.php"
cp "$SRC_BASE" "$DEST_DIR/base.php"
cp "$SRC_REVIEW" "$DEST_DIR/review.php"
grep -q "$PATCH" "$DEST_ROOT"
grep -q "READONLY REVIEW ACTIVE" "$DEST_DIR/review.php"
grep -q "EXECUTE DISABLED" "$DEST_DIR/review.php"
echo "PATCH=$PATCH"
echo "APPLY=PASS"
echo "PHP_LINT=PASS"
echo "EXECUTE=DISABLED"
echo "PUBLIC_SITE_CHANGED=NO"
