#!/usr/bin/env bash
set -euo pipefail
PATCH="TAMIYOUZ-WP-DEVELOPER-HUB-V1_0_3-SAFE-BOOTSTRAP"
ROOT="${WP_ROOT:-$PWD}"
BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_ROOT="$BASE/src/tamiyouz-developer-hub.php"
SRC_ADMIN="$BASE/src/tamiyouz-developer-hub/admin.php"
DEST_ROOT="$ROOT/wp-content/mu-plugins/tamiyouz-developer-hub.php"
DEST_DIR="$ROOT/wp-content/mu-plugins/tamiyouz-developer-hub"
php -l "$SRC_ROOT"
php -l "$SRC_ADMIN"
mkdir -p "$DEST_DIR"
[[ -f "$DEST_ROOT" ]] && cp -a "$DEST_ROOT" "$DEST_ROOT.bak.$(date +%Y%m%d-%H%M%S)"
cp "$SRC_ROOT" "$DEST_ROOT"
cp "$SRC_ADMIN" "$DEST_DIR/admin.php"
grep -q "TAMIYOUZ-WP-DEVELOPER-HUB-V1_0_3-SAFE-BOOTSTRAP" "$DEST_ROOT"
echo "PATCH=$PATCH"
echo "APPLY=PASS"
echo "PHP_LINT=PASS"
echo "SYNC_ACTIONS=DISABLED"
