#!/usr/bin/env bash
set -euo pipefail
PATCH="TAMIYOUZ-WP-DEVELOPER-HUB-V1_2-CONTROLLED-BASELINE-PUSH"
ROOT="${WP_ROOT:-$PWD}"
BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST_ROOT="$ROOT/wp-content/mu-plugins/tamiyouz-developer-hub.php"
DEST_DIR="$ROOT/wp-content/mu-plugins/tamiyouz-developer-hub"
for f in "$BASE/src/tamiyouz-developer-hub.php" "$BASE/src/tamiyouz-developer-hub/base.php" "$BASE/src/tamiyouz-developer-hub/review.php"; do php -l "$f"; done
mkdir -p "$DEST_DIR"
[[ -f "$DEST_ROOT" ]] && cp -a "$DEST_ROOT" "$DEST_ROOT.bak.$(date +%Y%m%d-%H%M%S)"
[[ -f "$DEST_DIR/base.php" ]] && cp -a "$DEST_DIR/base.php" "$DEST_DIR/base.php.bak.$(date +%Y%m%d-%H%M%S)"
[[ -f "$DEST_DIR/review.php" ]] && cp -a "$DEST_DIR/review.php" "$DEST_DIR/review.php.bak.$(date +%Y%m%d-%H%M%S)"
cp "$BASE/src/tamiyouz-developer-hub.php" "$DEST_ROOT"
cp "$BASE/src/tamiyouz-developer-hub/base.php" "$DEST_DIR/base.php"
cp "$BASE/src/tamiyouz-developer-hub/review.php" "$DEST_DIR/review.php"
grep -q "$PATCH" "$DEST_ROOT"
grep -q "$PATCH" "$DEST_DIR/review.php"
grep -q "Execute Reviewed Baseline Push" "$DEST_DIR/review.php"
echo "PATCH=$PATCH"
echo "APPLY=PASS"
echo "PHP_LINT=PASS"
echo "BASELINE_PUSH=CONTROLLED"
echo "PULL_SYNC_EXECUTE=DISABLED"
